rp.endpoint = https://reportportal.epam.com
rp.api.key = api-key_URX7q35WTkGQ0U1yeHDRbutEOIVmWAv3GQZ7GI0mUkQ4pakoq5eq1sfiNDLj9YMv
rp.launch = Yahoo_Mail_Test
rp.project = kydralieva_personal
rp.enable = true
